# CMake generated Testfile for 
# Source directory: D:/Inbox/GitHub Repos/retrofactory/tests
# Build directory: D:/Inbox/GitHub Repos/retrofactory/build_win/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(placeholder_run "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Debug/retrofactory_placeholder_test.exe")
  set_tests_properties(placeholder_run PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;12;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(placeholder_run "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Release/retrofactory_placeholder_test.exe")
  set_tests_properties(placeholder_run PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;12;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(placeholder_run "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/MinSizeRel/retrofactory_placeholder_test.exe")
  set_tests_properties(placeholder_run PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;12;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(placeholder_run "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/RelWithDebInfo/retrofactory_placeholder_test.exe")
  set_tests_properties(placeholder_run PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;12;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
else()
  add_test(placeholder_run NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(determinism_save_load "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Debug/test_save_load.exe")
  set_tests_properties(determinism_save_load PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;31;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(determinism_save_load "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Release/test_save_load.exe")
  set_tests_properties(determinism_save_load PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;31;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(determinism_save_load "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/MinSizeRel/test_save_load.exe")
  set_tests_properties(determinism_save_load PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;31;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(determinism_save_load "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/RelWithDebInfo/test_save_load.exe")
  set_tests_properties(determinism_save_load PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;31;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
else()
  add_test(determinism_save_load NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(core_world "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Debug/test_world.exe")
  set_tests_properties(core_world PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;50;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(core_world "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/Release/test_world.exe")
  set_tests_properties(core_world PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;50;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(core_world "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/MinSizeRel/test_world.exe")
  set_tests_properties(core_world PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;50;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(core_world "D:/Inbox/GitHub Repos/retrofactory/build_win/tests/RelWithDebInfo/test_world.exe")
  set_tests_properties(core_world PROPERTIES  _BACKTRACE_TRIPLES "D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;50;add_test;D:/Inbox/GitHub Repos/retrofactory/tests/CMakeLists.txt;0;")
else()
  add_test(core_world NOT_AVAILABLE)
endif()
