#include "scaffold.h"

#include "system/types.h"

#include <cstdio>
#include <errno.h>
#include <cstring>
#include <sys/stat.h>
#ifdef _WIN32
#include <direct.h>
#endif

static bool ensure_dir(const char *path)
{
#ifdef _WIN32
    return _mkdir(path) == 0 || errno == EEXIST;
#else
    return mkdir(path, 0755) == 0 || errno == EEXIST;
#endif
}

int mod_scaffold_main(int argc, char **argv)
{
    if (argc < 2)
    {
        std::printf("Usage: mod_scaffold <mod_name>\n");
        return 1;
    }

    const char *name = argv[1];
    char dir[128];
    std::snprintf(dir, sizeof(dir), "mods/%s", name);
    ensure_dir("mods");
    if (!ensure_dir(dir))
    {
        std::printf("Failed to create directory %s\n", dir);
        return 1;
    }

    char manifest_path[160];
    std::snprintf(manifest_path, sizeof(manifest_path), "%s/manifest.json", dir);

    std::FILE *manifest = std::fopen(manifest_path, "wb");
    if (manifest == 0)
    {
        std::printf("Failed to open %s for writing\n", manifest_path);
        return 1;
    }

    std::fprintf(manifest, "{\n  \"name\": \"%s\",\n  \"version\": \"0.1.0\",\n  \"description\": \"Generated by mod_scaffold\"\n}\n", name);
    std::fclose(manifest);

    char proto_dir[192];
    std::snprintf(proto_dir, sizeof(proto_dir), "%s/prototypes", dir);
    ensure_dir(proto_dir);

    const char *files[] = {"entities.json", "networks.json", "recipes.json", "research.json", "worldgen.json"};
    u32 i;
    for (i = 0u; i < sizeof(files) / sizeof(files[0]); ++i)
    {
        char path[256];
        std::snprintf(path, sizeof(path), "%s/%s", proto_dir, files[i]);
        std::FILE *f = std::fopen(path, "wb");
        if (f)
        {
            std::fprintf(f, "{\n  \"items\": []\n}\n");
            std::fclose(f);
        }
    }

    std::printf("Created mod scaffold at %s\n", dir);
    return 0;
}

int main(int argc, char **argv)
{
    return mod_scaffold_main(argc, argv);
}
